import "../styles/globals.css";
import type { AppProps } from "next/app";
import { Box, ChakraProvider, Container } from "@chakra-ui/react";
import Head from "next/head";
import Navbar from "../components/NavBar";
import theme from "../libs/theme";
import Fonts from "../components/Fonts";
import { AnimatePresence } from "framer-motion";

if (typeof window !== "undefined") {
  window.history.scrollRestoration = "manual";
}

function MyApp({ Component, pageProps, router }: AppProps) {
  return (
    <Box as="main" pb={8}>
      <Head>
        <title>HoangDai - Homepage</title>
        <meta name="viewport" content="witdth=device-with, initial-scale=1" />
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="/40_406071_cute_pineapple_drawing_Lbq_icon.ico"
        />
      </Head>
      <ChakraProvider theme={theme}>
        <Fonts />
        <Navbar path={router.asPath} />

        <Container maxW="container.md" pt={14}>
          <AnimatePresence
            exitBeforeEnter
            initial={true}
            onExitComplete={() => {
              if (typeof window !== "undefined") {
                window.scrollTo({ top: 0 });
              }
            }}
          >
            <Component {...pageProps} key={router.route} />
          </AnimatePresence>
        </Container>
      </ChakraProvider>
    </Box>
  );
}

export default MyApp;
