import "../styles/globals.css";
import type { AppProps } from "next/app";
import { Box, Container } from "@chakra-ui/react";
import Head from "next/head";

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <Box as="main" pb={8}>
      <Head>
        <title>HoangDai - Homepage</title>
        <meta name="viewport" content="witdth=device-with, initial-scale=1" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container></Container>
      <Component {...pageProps} />
    </Box>
  );
}

export default MyApp;
